export const FLOOR_IMAGES = {
  hero: "/epoxy/hero-concrete-architecture.jpg",
  showroom: "/polsihed/Services-Salt-and-Pepper.jpg",
  warehouse: "/epoxy/graphite-epoxy-flake.avif",
  detail: "/polsihed/Services-Full-Stone-Exposure.jpg",
  interior: "/polsihed/Services-Salt-and-Pepper.jpg",
  workshop: "/epoxy/basalt-epoxy-flake.avif",
  honed: "/polsihed/honed%20concrete.jpg",
  nilExposure: "/polsihed/nil%20exposure.jpg",
  saltPepper: "/polsihed/Services-Salt-and-Pepper.jpg",
  mediumExposure: "/polsihed/Medium%20exposure.jpeg",
  fullStone: "/polsihed/Services-Full-Stone-Exposure.jpg",
  epoxyGraphite: "/epoxy/graphite-epoxy-flake.avif",
  workCottesloe: "/examples/Cott.png",
  workOsbornePark: "/examples/OsiPark2.png",
  workKewdale: "/examples/Kewdale.png",
  workPeppermintGrove: "/examples/pepgrove.png",
  workNorthPerthCafe: "/examples/NPCAFE.png",
  workFremantleLoft: "/examples/freo.png",
  workSubiacoGallery: "/examples/SUBI.png",
  workMidlandWarehouse: "/examples/midland.png",
  workGrindSeal: "/polsihed/grind%20and%20seal.webp",
  workPolished: "/examples/Cott.png",
  workHoned: "/examples/OsiPark2.png",
  workEpoxyWanneroo: "/examples/Epoxy-Flake-Floor-Wanneroo.avif",
  workEpoxyGarage: "/examples/epoxy-flake-garage-banksia-grove.avif",
  workExposed: "/examples/Kewdale.png",
};

export const WORK_EXAMPLE_IMAGES = [
  ["Cottesloe Residence", "/examples/Cott.png"],
  ["Osborne Park Showroom", "/examples/OsiPark2.png"],
  ["Kewdale Warehouse", "/examples/Kewdale.png"],
  ["Peppermint Grove House", "/examples/pepgrove.png"],
  ["North Perth Cafe", "/examples/NPCAFE.png"],
  ["Fremantle Loft", "/examples/freo.png"],
  ["Subiaco Gallery", "/examples/SUBI.png"],
  ["Midland Warehouse", "/examples/midland.png"],
  ["Polished concrete floor", "/examples/polished-concrete-floor-perth.avif"],
  ["Honed concrete finish", "/examples/honed-concrete-floor-finish-perth.avif"],
  ["Epoxy flake floor, Wanneroo", "/examples/Epoxy-Flake-Floor-Wanneroo.avif"],
  ["Epoxy flake garage, Banksia Grove", "/examples/epoxy-flake-garage-banksia-grove.avif"],
  ["Bullseye garage floor, Kallaroo", "/examples/epoxy-flake-garage-floor-bullseye-kallaroo-perth.avif"],
  ["Cookies and cream garage, Banksia Grove", "/examples/epoxy-flake-garage-floor-cookies-and-cream-Banksia-Grove.avif"],
  ["Epoxy flake garage, Joondalup", "/examples/epoxy-flake-garage-floor-joondalup-perth.avif"],
  ["Epoxy flake pool area, Mindarie", "/examples/epoxy-flake-pool-area-sandstone-mindarie-perth.avif"],
  ["Exposed aggregate driveway, Ashby", "/examples/exposed-aggregate-driveway-ashby-perth.avif"],
  ["Exposed concrete pathway, Burns Beach", "/examples/exposed-concrete-pathway-burns-beach-perth.avif"],
  ["Metallic epoxy floor, Wanneroo", "/examples/metallic-epoxy-floor-wanneroo-perth.avif"],
  ["Epoxy flake granny flat, Mindarie", "/examples/epoxy-flake-floor-granny-flat-mindarie-perth.avif"],
] as const;

export const ULTRA_FLAKE_IMAGES = [
  ["Blue Storm", "/epoxy/blue-storm-epoxy-flake.avif"],
  ["Bullseye", "/epoxy/bullseye-epoxy-flake.avif"],
  ["Camo", "/epoxy/camo-epoxy-flake.avif"],
  ["Cookies & Cream", "/epoxy/cookies-and-cream-epoxy-flake.avif"],
  ["Cookies & Cream (Small)", "/epoxy/cookies-and-cream-small-epoxy-flake.avif"],
  ["Eggshell", "/epoxy/eggshell-epoxy-flake.avif"],
  ["Foil", "/epoxy/foil-epoxy-flake.avif"],
  ["Graphite", "/epoxy/graphite-epoxy-flake.avif"],
  ["Graphite (Light)", "/epoxy/graphite-light-epoxy-flake.avif"],
  ["Heritage", "/epoxy/heritage-epoxy-flake.avif"],
  ["Night Sky", "/epoxy/night-sky-epoxy-flake.avif"],
  ["Suede", "/epoxy/suede-epoxy-flake.avif"],
  ["Red Earth", "/epoxy/red-earth-epoxy-flake.avif"],
  ["Biscuit", "/epoxy/biscuit-epoxy-flake.avif"],
  ["Carbon", "/epoxy/carbon-black-epoxy-flake.avif"],
  ["Ice", "/epoxy/ice-epoxy-flake.avif"],
] as const;

export const HYPER_FLAKE_IMAGES = [
  ["Basalt", "/epoxy/basalt-epoxy-flake.avif"],
  ["Coral", "/epoxy/coral-epoxy-flake.avif"],
  ["Quarry", "/epoxy/quarry-epoxy-flake.avif"],
  ["River Stone", "/epoxy/river-stone-epoxy-flake.avif"],
  ["Sand Stone", "/epoxy/sand-stone-epoxy-flake.avif"],
  ["Silver Stone", "/epoxy/silver-stone-epoxy-flake.avif"],
] as const;

export const POLISHED_CONCRETE_IMAGES = [
  ["Nil exposure", "/polsihed/nil%20exposure.jpg"],
  ["Salt and pepper", "/polsihed/Services-Salt-and-Pepper.jpg"],
  ["Medium exposure", "/polsihed/Medium%20exposure.jpeg"],
  ["Full stone exposure", "/polsihed/Services-Full-Stone-Exposure.jpg"],
  ["Honed concrete", "/polsihed/honed%20concrete.jpg"],
] as const;
